### ISSUE TITLE
Keep/Drop dice

### ISSUE THREAD

**Issue by lemtzas** [lemtzas/rollem-discord#9]
Ability to keep and drop dice in a set.
Keep/Drop Highest and Keep/Drop Lowest.

https://wiki.roll20.net/Dice_Reference#Keep_.2F_Drop_Dice_.28B.2CF.29_khN.2FklN.2FdhN.2FdlN

**Comment by CraziFuzzy** [comment]
Very much would like this as well.

**Comment by lemtzas** [comment]
This is now in the beta bot.
* Keep Highest N `10d5k5` `10d5kh5` - `k` is a shortcut for `kh`
* Drop Lowest N `10d5d5` `10d5dl5` - `d` is a shortcut for `dl`
* Drop Highest N `10d5dh5`
* Keep Lowest N `10d5kl5`
* Disable sorting `10d3k5ns`
* With exploding dice `10d3!k5`
* For D&D-style statgen `6#4d6d1`
